### ISSUE TITLE
Missing binaries for 1.36.0

### ISSUE THREAD

**Issue by odsod** [googleapis/api-linter#1019]
The latest release, https://github.com/googleapis/api-linter/releases/tag/v1.36.0, does not have any binaries uploaded to it.

**Comment by loeffel-io** [comment]
+1

**Comment by noahdietz** [comment]
Ack

**Comment by noahdietz** [comment]
https://github.com/googleapis/api-linter/releases/tag/v1.36.1 has binaries generated by CI so I've fixed that. I will upload binaries for v1.36.0 manually though, then close this.

**Comment by noahdietz** [comment]
I've added binaries to v1.36.0 using that tag & the proper `version` constant for the `api-linter version` command.
