### ISSUE TITLE
Can users disable specific problems rather than just rules?

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/api-linter#102]
Right now, there is a lot of boilerplate in rule-writing, which largely stems from duplicate setup.
For example, if writing rules for AIP-131, I have to ignore methods not starting with `Get-`, parse out the RPC, possibly traverse to the input and output, etc. All of these things are reasonable, but doing them 8-10 times is tedious.

Right now, the reason we have to do this is because users can only disable rules, so if I have multiple problems covered by the same rule, they are "all or nothing" for users.

Can we make it possible to disable (or ignore) specific problems, perhaps by giving them identifiers and namespacing under rules?

**Comment by robcapo** [comment]
I think the design of the linter is predicated on the assumption that `Rule`s define classes or categories of `Problem`s. There's very little distinction between the two, aside from the fact that `Problem`s can occur at different locations in the file, and may have corresponding messages based on the specific violations of the `Rule`. Do you think we could solve this problem by removing some of the boilerplate from implementing `Rule`s?

Some ideas:

## Convenience method for sharing RuleInfo across rules, e.g.:

```go
func (r RuleInfo) WithSubName(n RuleName) RuleInfo {
  r.Name = strings.Join([]string{string(r.Name), string(n)}, nameSeparator)
  return r
}
func (r RuleInfo) WithUri(uri string) RuleInfo {
  r.URI = uri
  return r
}
func (r RuleInfo) WithDescription(desc string) RuleInfo {
  r.Description = desc
  return r
}
```

## Combine `CallbackRule` and `Callbacks`

I don't think `Callback` is likely to be used by itself. It's juts an extra layer of indirection which leads to 2 more lines of boilerplate for each rule. We can instead move the specific descriptor callbacks onto the `CallbackRule`.

## Example Rule

This would enable sharing of common RuleInfo elements like:

my_rules.go
```go
var aip132Info RuleInfo = lint.RuleInfo{
	Name:         lint.NewRuleName("core", "0132", "request_message"),
	RequestTypes: []lint.RequestType{lint.ProtoRequest},
	Description:  "best practices for writing List methods",
	URI:          "https://aip.dev/132",
}

var guidanceUri string = "https://aip.dev/132#guidance"
var requestMessageUri string = "https://aip.dev/132#request-message"

func checkListRequestMessageName() lint.Rule {
	return &descriptor.CallbackRule{
		RuleInfo: aip132Info.WithSubName("name").WithUri(guidanceUri).WithDescription("check that List RPCs have appropriate request messages")
		MethodCallback: func(m p.MethodDescriptor, s lint.DescriptorSource) (problems []lint.Problem, err error) {
			// .. your implementation here
		}
	}
}

func checkListRequestMessageParentField() lint.Rule {
	return &descriptor.CallbackRule{
		RuleInfo: aip132Info.WithSubName("parent_field").WithUri(requestMessageUri).WithDescription("check that a parent field is present")
		MethodCallback: func(m p.MethodDescriptor, s lint.DescriptorSource) (problems []lint.Problem, err error) {
			// .. your implementation here
		}
	}
}

```

## Add helper for executing Rule.Lint in testutil

I think we all agree that most of the pain is in tests.

```go
func MustLint(t *testing.T, r lint.Rule, f FileDescriptorSpec) []Problem {
	p := MustCreateFileDescriptorProto(t, f)
	req, err := lint.NewProtoRequest(p, nil)
	if err != nil {
		t.Fatalf("Failed to create proto request because: %s", err)
	}

	p, err := r.Lint(req)
	if err != nil {
		t.Fatalf("Failed to lint Request because: %s", err)
	}

	return p
}
```

## Example test

```go
func TestGetRequestMessageNameField(t *testing.T) {
	tmpl := `syntax = "proto3";

	service Aip131 {
		rpc GetFoo(GetFooRequest) returns (Foo);
	}

	message GetFooRequest {
		{{.NameFieldType}} {{.NameFieldName}} = 1;
	}

	message Foo {}`

	tests := []struct {
		NameFieldType string
		NameFieldName string
		problemCount  int
		startLine     int
	}{
		{"string", "name", 0, -1},
		{"string", "resource", 1, 7},
		{"bytes", "name", 1, 8},
	}

	rule := checkGetRequestMessageNameField()
	errPrefix := "AIP-131 Request Name Field"

	for _, test := range tests {
		resp := testutil.MustLintFileDescriptorSpec(t, rule, testutil.FileDescriptorSpec{
			Template: tmpl,
			Data:     test,
		})

		if got, want := len(resp), test.problemCount; got != want {
			t.Errorf("%s: got %d problems, but want %d", errPrefix, got, want)
		}

		if len(resp) > 0 {
			if got, want := resp[0].Location.Start.Line, test.startLine; got != want {
				t.Errorf("%s: got location starting with %d, but want %d", errPrefix, got, want)
			}
		}
	}
}
```

WDYT?

**Comment by lukesneeringer** [comment]
Here are the problems I want to solve:

* Right now, rules are extremely repetitive.
* Right now, writing a series of rules for a single AIP feels like this:
  * First rule: do A, do B, check C, return problem
  * Second rule: do A, do B, do C, check D, return problem
  * Third rule: do A, do B, do C, do D, check E, return problem
  * Fourth rule: do A, do B, do C, do D, do E, check F, return problem
  * ...the code would be much cleaner to write if these things were done once (and more efficient also).

**Comment by lukesneeringer** [comment]
Following up on this...I agree with that @robcapo's solution is probably likely to make this issue _better_, but I actually still want to push for what I am proposing. It effectively makes there be "groups of rules" (most likely grouped by an AIP, or at most two groups per AIP in cases where we need to spilt e.g. RPC-based rules vs. message-based rules), which can be disabled at once, and individual problems, which can be disabled piecemeal.

I think this could be implemented somewhat easily -- essentially, if a problem is disabled, the rule still runs, and the linter just has some post-processing that throws away any problems it does not care about.

**Comment by robcapo** [comment]
So, I originally proposed putting the meta-information on the problems instead of the rules, but the argument against it was that by including it on the rules, we could have the CLI expose all of the possible output identifiers to the user to help them write a config. [Here's an implementation](https://github.com/googleapis/api-linter/pull/48) that was ultimately closed because higher priority issues were merged first and it became out of sync, but I think the intention is still to add something like it. If the meta information goes on the problems, it would be much harder for a user to see what things are configurable (i.e. they would need to look at rule implementations). The hope was that someone could run a command line `linter listrules`, get a list of descriptions, AIPs, identifiers, etc. and say "yeah I want to enforce this" and enable it in their config. If each Rule encompasses many problems, and the user wants to disable some of them, the only way to achieve it is to look at source code. This would also prevent future UI iterations that would benefit from programatically discovering all the possible outputs (not sure how likely it is for the UI to evolve).

I want to also mention that there's nothing preventing you from sharing logic across rules –you're free to encapsulate the repetitive logic in functions and call them from different rules. That would likely clean up your rules quite a bit (and maybe even make them self documenting). I don't think the efficiency argument is super relevant, as the cost of compiling the protos is likely much larger than any of the rules, and the compilation phase only happens once for each linter run (it's not related to the number of rules). I haven't benchmarked this myself, but my gut says we're not going to save much time by iterating over descripters a few less times. Furthermore, this isn't a performance critical tool.

I agree that the implementation would probably be straightforward, but I'm more concerned about the impact that it could have on the complexity of configuration (users and the linter both now need to consider two types of identifiers, rule identifiers and problem identifiers).

I'm not writing off this suggestion by any means. Just wanted to provide more context for the counter-argument, as my initial feeling was the same as yours (for much of the same reasons), but I was convinced that there was value in doing it the way it is now.

**Comment by lukesneeringer** [comment]
> So, I originally proposed putting the meta-information on the problems instead of the rules, but the argument against it was that by including it on the rules, we could have the CLI expose all of the possible output identifiers to the user to help them write a config.

I do not see why that changes. What I am asking for is that _both_ rules _and_ problems get meta-information. I would expect that a problem's information is fundamentally "appended" to the rule's meta-information.

> The hope was that someone could run a command line linter listrules, get a list of descriptions, AIPs, identifiers, etc. and say "yeah I want to enforce this" and enable it in their config. If each Rule encompasses many problems, and the user wants to disable some of them, the only way to achieve it is to look at source code.

I take your point here. We could ameliorate this somewhat by having the rule know what problems it is able to return.

> I want to also mention that there's nothing preventing you from sharing logic across rules –you're free to encapsulate the repetitive logic in functions and call them from different rules.

In theory, yes, but if you go do that in practice, it saves very little. You have a bunch of functions that have three to four lines each and have to do baton-passes of arguments and return values and such, and then it gets harder to read a rule because you have to bounce around the file.

**Comment by robcapo** [comment]
> I take your point here. We could ameliorate this somewhat by having the rule know what problems it is able to return.

Could you provide some samples of what you have in mind for the changes to `RuleInfo` and returning `Problem`s? That should get to the rub of what this will look like for rule developers and users.

**Comment by lukesneeringer** [comment]
I guess what I would hope is that the code would look more like this:

```go
// Get messages should have a properly named Request message.
func checkGetRequestMessageName() lint.Rule {
	return &descriptor.CallbackRule{
		RuleInfo: lint.RuleInfo{
			Name:         lint.NewRuleName("core", "0131"),
			Description:  "check that Get RPCs have appropriate request messages",
			RequestTypes: []lint.RequestType{lint.ProtoRequest},
			URI:          "https://aip.dev/131#guidance",
		},
		Callback: descriptor.Callbacks{
			MethodCallback: func(m p.MethodDescriptor, s lint.DescriptorSource) (problems []lint.Problem, err error) {
				// We only care about Get methods for the purpose of this rule;
				// ignore everything else.
				if !isGetMethod(m) {
					return
				}

				// Rule check: Establish that for methods such as `GetFoo`, the request
				// message is named `GetFooRequest`.
				methodName := string(m.Name())
				requestMessageName := string(m.Input().Name())
				correctRequestMessageName := methodName + "Request"
				if requestMessageName != correctRequestMessageName {
					problems = append(problems, lint.Problem{
						Name: "request-message-name",
						Message: fmt.Sprintf(
							"Get RPCs should have a request message named after the RPC, such as %q.",
							correctRequestMessageName,
						),
						Suggestion: correctRequestMessageName,
						Descriptor: m,
					})
				}

				// Rule check: Establish that a name field is present.
				nameField := m.Input().Fields().ByName("name")
				if nameField == nil {
					problems = append(problems, lint.Problem{
						Name: "no-name-field",
						Message:    fmt.Sprintf("method %q has no `name` field", m.Name()),
						Descriptor: m.Input(),
					})
					return problems, nil
				}

				// Rule check: Establish that the name field is a string.
				if nameField.Kind() != p.StringKind {
					problems = append(problems, lint.Problem{
						Name: "request-message-name-type",
						Message:    "`name` field on Get RPCs should be a string",
						Descriptor: nameField,
					})
				}

				// Rule check: Establish that there are no unexpected fields.
				allowedFields := map[string]struct{}{
					"name":      {}, // AIP-131
					"read_mask": {}, // AIP-157
					"view":      {}, // AIP-157
				}
				fields := m.Input().Fields()
				for i := 0; i < fields.Len(); i++ {
					field := fields.Get(i)
					if _, ok := allowedFields[string(field.Name())]; !ok {
						problems = append(problems, lint.Problem{
							Name: "unexpected-field",
							Message: fmt.Sprintf(
								"Get RPCs should only only contain fields explicitly described in AIPs, not %q.",
								string(field.Name()),
							),
							Descriptor: field,
						})
					}
				}

				// Rule check: Establish that for methods such as `GetFoo`, the response
				// message is named `Foo`.
				responseMessageName := string(m.Output().Name())
				if correctResponseMessageName := methodName[3:]; correctResponseMessageName != responseMessageName {
					problems = append(problems, lint.Problem{
						Name: "response-message-name",
						Message: fmt.Sprintf(
							"Get RPCs should have the corresponding resource as the response message, such as %q.",
							correctResponseMessageName,
						),
						Suggestion: correctResponseMessageName,
						Descriptor: m,
					})
				}

				return problems, nil
			},
		},
	}
}
```

This approach would still allow either rules or problems to be toggled, and it cuts the amount of code by about 35%.

**Comment by robcapo** [comment]
In this case you wouldn't be able to run a CLI to enumerate out all of the possible problems that a Rule returns. In other words, although you can disable any `Problem` within the `Rule`, the only way to find them is to look through the source code.

One way I might solve this with shared code:
```
func checkGetRequestMessageRule(name string, f func(p.MethodDescriptor, lint.DescriptorSource) ([]lint.Problem, error)) lint.Rule {
	return &descriptor.CallbackRule{
		RuleInfo: lint.RuleInfo{
			Name:         lint.NewRuleName("core", "0131", name),
			Description:  "check that Get RPCs have appropriate request messages",
			RequestTypes: []lint.RequestType{lint.ProtoRequest},
			URI:          "https://aip.dev/131#guidance",
		},
		Callback: descriptor.Callbacks{
			MethodCallback: func(m p.MethodDescriptor, s lint.DescriptorSource) (problems []lint.Problem, err error) {
				// We only care about Get methods for the purpose of this rule;
				// ignore everything else.
				if !isGetMethod(m) {
					return
				}
				return f(m, s)
			}
		},
	}
}

func getFooRequestRule() lint.Rule {
	return checkGetRequestMessageRule(
		"request-message-name",
		func(m p.MethodDescriptor, s lint.DescriptorSource) (problems []lint.Problem, err error) {
				// Rule check: Establish that for methods such as `GetFoo`, the request
				// message is named `GetFooRequest`.
				methodName := string(m.Name())
				requestMessageName := string(m.Input().Name())
				correctRequestMessageName := methodName + "Request"
				if requestMessageName != correctRequestMessageName {
					problems = append(problems, lint.Problem{
						Name: "request-message-name",
						Message: fmt.Sprintf(
							"Get RPCs should have a request message named after the RPC, such as %q.",
							correctRequestMessageName,
						),
						Suggestion: correctRequestMessageName,
						Descriptor: m,
					})
				}
		},
	)
}

func nameFieldPresentRule() lint.Rule {
	return checkGetRequestMessageRule(
		"no-name-field",
		func(m p.MethodDescriptor, s lint.DescriptorSource) (problems []lint.Problem, err error) {
				// Rule check: Establish that a name field is present.
				nameField := m.Input().Fields().ByName("name")
				if nameField == nil {
					problems = append(problems, lint.Problem{
						Name: "no-name-field",
						Message:    fmt.Sprintf("method %q has no `name` field", m.Name()),
						Descriptor: m.Input(),
					})
					return problems, nil
				}
		},
	)
}

func requestMessageNameType() lint.Rule {
	return checkGetRequestMessageRule(
		"request-message-name-type",
		func(m p.MethodDescriptor, s lint.DescriptorSource) (problems []lint.Problem, err error) {
				// Rule check: Establish that the name field is a string.
				if nameField.Kind() != p.StringKind {
					problems = append(problems, lint.Problem{
						Name: "request-message-name-type",
						Message:    "`name` field on Get RPCs should be a string",
						Descriptor: nameField,
					})
				}
		},
	)
}

func noUnexpectedFieldsRule() lint.Rule {
	return checkGetRequestMessageRule(
		"unexpected-field",
		func(m p.MethodDescriptor, s lint.DescriptorSource) (problems []lint.Problem, err error) {
				// Rule check: Establish that there are no unexpected fields.
				allowedFields := map[string]struct{}{
					"name":      {}, // AIP-131
					"read_mask": {}, // AIP-157
					"view":      {}, // AIP-157
				}
				fields := m.Input().Fields()
				for i := 0; i < fields.Len(); i++ {
					field := fields.Get(i)
					if _, ok := allowedFields[string(field.Name())]; !ok {
						problems = append(problems, lint.Problem{
							Name: "unexpected-field",
							Message: fmt.Sprintf(
								"Get RPCs should only only contain fields explicitly described in AIPs, not %q.",
								string(field.Name()),
							),
							Descriptor: field,
						})
					}
				}
		},
	)
}

func responseMessageNameRule() lint.Rule {
	return checkGetRequestMessageRule(
		"response-message-name",
		func(m p.MethodDescriptor, s lint.DescriptorSource) (problems []lint.Problem, err error) {
				// Rule check: Establish that for methods such as `GetFoo`, the response
				// message is named `Foo`.
				responseMessageName := string(m.Output().Name())
				if correctResponseMessageName := methodName[3:]; correctResponseMessageName != responseMessageName {
					problems = append(problems, lint.Problem{
						Message: fmt.Sprintf(
							"Get RPCs should have the corresponding resource as the response message, such as %q.",
							correctResponseMessageName,
						),
						Suggestion: correctResponseMessageName,
						Descriptor: m,
					})
				}
		},
	)
}
```

Sorry about the unmatched indentation, and this code definitely won't build (I wrote it in the GitHub textarea while copy pasting your example), but I hope this illustrates my point. Each of these rules only has 5ish lines of boilerplate, and the advantage here is that each set of `Problem`s is registered with the linter explicitly, rather than being hidden in the implementation of the rule's source code. Basically we just need to weigh the convenience to the developer of having fewer lines of boilerplate against the convenience of the user being able to see all the possible outputs of the linter without reading source code.

WDYT?

**Comment by lukesneeringer** [comment]
Why can you not find them except through the source code? The Problems have a name, which could be reported, and then you know the name to disable.

**Comment by robcapo** [comment]
I'm referring to my statement earlier:
> argument against it was that by including it on the rules, we could have the CLI expose all of the possible output identifiers to the user to help them write a config

There's a valid argument that the `Rule` itself could point to more documentation about the identifiers of the problems it returns, so the user could decide from there how to configure it, but in general they will be less discoverable.

I agree that there's value to grouping, but that's already possible with the way that `RuleName`s work, you can enable or disable an entire group of `Rule`s as long as they share a `RuleName` prefix.

I also agree that there's certain usecases that would benefit from having identifiers for `Problem`s, but there's also a cost, and so all I'm saying is that this is a trade-off that you guys, as the owners of the linter, should decide on. What you're suggesting is definitely possible, and it's probably not a ton of effort, but it changes the semantics of what a `Rule` vs `Problem` is (they now have some overlapping responsibility in identifying a "class" of problems, which was previously the `Rule`s job), so you may need to rethink some of the assumptions were made in the initial design. Specifically, what's contained in `RuleInfo`, what an input configuration looks like, and what the output of the linter looks like.

**Comment by lukesneeringer** [comment]
I think after giving it more thought, I am slowly coming around to @robcapo's position here. I still want some consistent way to handle grouping logic within rules, but I think I may have another idea for it.
