### ISSUE TITLE
Validate that HTTPRules follow the path template syntax

### ISSUE THREAD

**Issue by acamadeo** [googleapis/api-linter#1049]
There's already an [existing rule](https://github.com/googleapis/api-linter/blob/c18f3154970793d9b984a376344d44e73ee4eb39/rules/aip0122/camel_case_uris.go#L27) that enforces the use of `camelCase` inside [HTTPRules](https://github.com/googleapis/googleapis/blob/16db2fb7fab4668bdfa09966513e03581d8f5e35/google/api/http.proto#L313). We could extend this by checking that the`HTTPRule` follows the path template syntax laid out [here](https://github.com/googleapis/googleapis/blob/16db2fb7fab4668bdfa09966513e03581d8f5e35/google/api/http.proto#L224).

**Comment by noahdietz** [comment]
Fixed by #1051. If I'm mistaken, please ask for it to be reopened.
