### ISSUE TITLE
Automatically detect Location based on Descriptor for a problem

### ISSUE THREAD

**Issue by robcapo** [googleapis/api-linter#107]
The [documentation for `Problem.Descriptor`](https://github.com/googleapis/api-linter/blob/master/lint/response.go#L35-L39) states that if Location is unset, we will use the location of the descriptor to set it automatically.

However, I don't believe we're currently doing this.

**Comment by lukesneeringer** [comment]
Pretty sure this is working; the tests definitely use the location line values that I expect.
