### ISSUE TITLE
Misleading wording in https://linter.aip.dev/140/base64 ("base64 fields")

### ISSUE THREAD

**Issue by prateek-0** [googleapis/api-linter#1094]
https://linter.aip.dev/140/base64 says

> This rule tries to enforce that base64 fields use the bytes type, as mandated by [AIP-140](https://aip.dev/140)

This seems misleading. I think it's trying to say that you should not have a "base64 field" at all, but if you need to represent bytes you should just use the "bytes" type directly, without involving any base64.

If you genuinely had the base64 encoding of anything populated in proto field, surely that field would be of type string, since the base64 encoding of anything is a string.

My understanding is that while using gRPC `bytes` will remain as `bytes`, but while using a REST API with JSON, `bytes` will get translated to a string using base64. However, that is only a property of how gRPC maps to REST API with JSON, and is not a good enough reason to refer to any `bytes` field as "a base64 field".

**Comment by noahdietz** [comment]
@prateek-0 thanks, but the linter just enforces what the AIP states. I think this issue belongs on the [AIP repo](https://github.com/aip-dev/google.aip.dev/issues) as it is directed at the guidance of using `bytes` vs. `string`.

I cannot transfer this issue between orgs, so I will close this one and you can open another there. Or consider posting on http://go/api-design-yaqs first, we are much more diligent about responding there.

Thanks

**Comment by prateek-0** [comment]
Even if the linter enforces what the AIP states, the wording of the linter (which is not the same as the wording in the AIP) is problematic.

Reading through https://linter.aip.dev/140/base64 and https://google.aip.dev/140#string-vs-bytes carefully, it is only the linter which refers to the concept of a "base64 field". This concept seems not clearly defined and problematic. Hence I'm reporting this bug to the place which first mentions this concept, which is the Linter and not the AIP.

One way to fix this could be to take the wording from the AIP and use it for the Linter:

"Services should use bytes when there is a need to send binary contents over the wire, and should not ask the user to manually base64-encode a field into a string field.

Details:

This rule checks the comments over each field. If “base64” is mentioned and the field is a string, it assumes that the intention was a need to send binary contents over the wire, and that the comment asks the user to manually base64-encode the binary contents into a string field."


*****

On a related note, in https://linter.aip.dev/140/base64 , the "Correct" code seems subtly wrong. It says

// The base64-encoded checksum.
  bytes checksum = 2;

But it should say

// The checksum.
  bytes checksum = 2;

Since in the "bytes checksum" field, the intention is to populate the bytes of the checksum directly, without any base64 or any other encoding.

**Comment by noahdietz** [comment]
@prateek-0 ok, fair enough. A contribution would be welcome here.
