### ISSUE TITLE
AIP-203: require field_behavior

### ISSUE THREAD

**Issue by toumorokoshi** [googleapis/api-linter#1102]
AIP-203 states:

> APIs should use the google.api.field_behavior annotation to describe well-understood field behavior, such as a field's being required, immutable, or output only:

This is not verified by the api-linter today.

**Comment by toumorokoshi** [comment]
likely we could force this by requiring that at least one of `required`, `optional`, `output_only`, or `input_only` is set.

**Comment by toumorokoshi** [comment]
side not for discussion: I'm not sure why `optional` and `input_only` is not a valid combination, but TBInvestigated.

**Comment by shwoodard** [comment]
Would this be ubiquitous or Cloud only?

**Comment by toumorokoshi** [comment]
I'd say in general these should be ubiquitous unless there's a good reason to scope it.

**Comment by shwoodard** [comment]
Are there other values that might be reasonable for the set? iirc there was additional values that tf uses.

**Comment by toumorokoshi** [comment]
fixed with #1149
