### ISSUE TITLE
AIP-121: require re-using proto message across CRUDL

### ISSUE THREAD

**Issue by toumorokoshi** [googleapis/api-linter#1103]
AIP-121 states:

> If the request to or the response from a standard method (or a custom method in the same service) is the resource or contains the resource, the resource schema for that resource across all methods must be the same.

**Comment by toumorokoshi** [comment]
this one is implicitly supported today, since all the AIP rules require that the method URI matches pattern annotation of the google.api.resource.

Also as outlined in [1103](https://github.com/googleapis/api-linter/issues/1104#issuecomment-1537186781) it's difficult to do checks that span multiple RPCs. 

I think in practice this isn't an issue so I'll remove it from the milestone, but keep in the backlog for a future milestone.

**Comment by noahdietz** [comment]
As we prepare for CS-2312, I'm triaging the associated milestone list. Moving this to the backlog milestone for the same reasons mentioned above.

**Comment by toumorokoshi** [comment]
For practical purposes I think this is enforced: a Create* needs to follow a specific pattern, and it fails if it can't find a resource and if the path doesn't match.

The only exception is for custom methods, and as we've discussed offline it's impossible to tell if a custom method operates on a single resource, or multiple resources (therein lies the term custom).

So I'm pretty confident we can close this as is.
