### ISSUE TITLE
AIP-121: require GET and LIST

### ISSUE THREAD

**Issue by toumorokoshi** [googleapis/api-linter#1104]
AIP-121 states: 

> A resource must support at minimum [Get](https://google.aip.dev/131): clients must be able to validate the state of resources after performing a mutation such as [Create](https://google.aip.dev/133), [Update](https://google.aip.dev/134), or [Delete](https://google.aip.dev/135).

> A resource must also support [List](https://google.aip.dev/132), except for [singleton resources](https://google.aip.dev/156) where more than one resource is not possible.

**Comment by toumorokoshi** [comment]
I took a brief look at this one, and it's a bit tricky with the  current architecture. Some notes:

- the current method of binding the method to the resource is to retrieve the output type from the RPC itself. I wanted to bind this linter check to the message, but you can't easily look up the RPCs attached to it.
- I was thinking of just traversing the file, but that's also difficult because the file doesn't necessarily contain the RPCs that depend on it (it's common to have message declarations separate from service definitions).

**Comment by toumorokoshi** [comment]
some more notes:

- we could look at the service, and RPCs defined in the same package.
- there are files that contain resources that are defined in the same proto file that are used by different services. 
- Service -> defined all RPCs, can use those to figure that.
  - look for Get / List for those.
  - collect all RPCs
- look at all return types? beyond standard method.
  - what is the value of a resource with only custom methods?
  - cloud build trigger could just have `:trigger` but must be gettable.

**Comment by toumorokoshi** [comment]
more feedback: start with get, add list later (prevent false positives, especially while singletons are allowed).

**Comment by noahdietz** [comment]
@toumorokoshi did you want to include this in CS-2312 since we skipped it in CS-2306?

**Comment by toumorokoshi** [comment]
The major issue with linting for LIST is [Singleton resources](https://google.aip.dev/156). Until we have a way to determine which are singletons and which are not, we can't enforce it.

Maybe a good use case for `google.api.resource`?

**Comment by noahdietz** [comment]
A _heuristic_ for identifying a singleton is if the resource pattern(s) end in a static segment (not an ID segment) e.g. `instances/{instance}/settings` where `/settings` being a static segment indicates it is a singleton.

I think this is pretty reliable.

**Comment by toumorokoshi** [comment]
you're right, that could work. I guess there's no harm in adding a linter rule that checks for `List` except for resources with that heuristic.

Also we may want to consider putting this one in Cloud: I think *all* resources benefit, but the absolute need for List seems like a cloud-specific need.

**Comment by noahdietz** [comment]
@toumorokoshi I'm not sure how we make this rule only for cloud without also making a Cloud Specific AIP. Since the Rule will be mapped to the AIP number `121`, that influences the name construction, and thus the rule documentation routing, configuration, etc.

If we want this guidance to only apply to Cloud, then I think we need to break out into its own AIP, also modifying the existing AIP-121 guidance to only require Get.

Can you explain why list is only important to Cloud? Thanks

**Comment by toumorokoshi** [comment]
> Can you explain why list is only important to Cloud? Thanks

I guess it's not *just* important to Cloud - from a usability standpoint any resource should be Listable or Gettable. We've already established that a Listable resource that is not Gettable forces the user to use filter to retrieve even a single resource, which is undesirable.

I'm fine with adding it as a rule.

**Comment by noahdietz** [comment]
Cool sounds good. We can come back to this if we get negative reports. Thanks!
