### ISSUE TITLE
request `{resource}_id` even if the resource is not declarative-friendly.

### ISSUE THREAD

**Issue by toumorokoshi** [googleapis/api-linter#1107]
Generally, having user-settable IDs is a better user experience, and it would be best to require them and exempt yourself in edge cases rather than not enforce it.

See https://github.com/aip-dev/google.aip.dev/pull/1019 which also recommends upgrading the guidance.

**Comment by SsomsakTH** [comment]
> Generally, having user-settable IDs is a better user experience, and it would be best to require them and exempt yourself in edge cases rather than not enforce it.
> 
> See https://github.com/aip-dev/google.aip.dev/pull/1019 which also recommends upgrading the guidance.

**Comment by SsomsakTH** [comment]
> Generally, having user-settable IDs is a better user experience, and it would be best to require them and exempt yourself in edge cases rather than not enforce it.
> 
> See https://github.com/aip-dev/google.aip.dev/pull/1019 which also recommends upgrading the guidance.

**Comment by SsomsakTH** [comment]
> Generally, having user-settable IDs is a better user experience, and it would be best to require them and exempt yourself in edge cases rather than not enforce it.
> 
> See https://github.com/aip-dev/google.aip.dev/pull/1019 which also recommends upgrading the guidance.
