### ISSUE TITLE
AIP-203: remove output-only check?

### ISSUE THREAD

**Issue by toumorokoshi** [googleapis/api-linter#1164]
Some users are reporting erroneous detection of the need for the `OUTPUT_ONLY` annotation, because the AIP-203::output-only check looks for the string "output.*only" and raises an error otherwise.

I wonder if this rule should be removed, especially with the advent of https://linter.aip.dev/203/field-behavior-required? I suppose it's possible to miss the field behavior, but it feels minimizing false positives is better.

**Comment by noahdietz** [comment]
This question applies to the same rule for each field_behavior value.

This was also reported/discussed in #892 fwiw.

**Comment by noahdietz** [comment]
I think we should just remove these checks now that we require it to be used everywhere.

**Comment by toumorokoshi** [comment]
+1, I'd approve that PR.
