### ISSUE TITLE
1.51.0-linux-amd64 rapidly consumes memory and does not complete

### ISSUE THREAD

**Issue by SanjayVas** [googleapis/api-linter#1174]
#### Environment details

  - Programming language: N/A
  - OS: Linux (Debian 11)
  - Language runtime version: N/A
  - Package version: 1.51.0-linux-amd64

#### Steps to reproduce

  1. Run api-linter
  
Worked fine using 1.47.0. I killed it when it hit 8 GiB.

**Comment by SanjayVas** [comment]
Can also reproduce on 1.50.0.

**Comment by SanjayVas** [comment]
1.48.0 appears to be the last working release.

**Comment by noahdietz** [comment]
Not sure if this is still an issue or not. We are well passed the problem release at this point. A reproduction would be useful if it is still an issue, but I will close for now unless it comes back.
