### ISSUE TITLE
GLIBC errors

### ISSUE THREAD

**Issue by ewhauser** [googleapis/api-linter#1317]
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by bazel-out/k8-opt-  exec-ST-13d3ddad9198/bin/tools/api_linter.runfiles/api_linter/api-linter)

#### Environment details

  - Programming language: Go
  - OS: Linux - Debian GNU/Linux 11 (bullseye)
  - Language runtime version: 1.20 
  - Package version: v1.60.0+

#### Steps to reproduce

1. Run API linter

Based on this Go [issue](https://github.com/golang/go/issues/58550), I believe the builds should be run with `CGO_ENABLED=0` since I don't think API linter uses cgo.

**Comment by noahdietz** [comment]
Thanks for the report, and apologies for the delay in responding. I've got a patch to update our release script to include this.

**Comment by noahdietz** [comment]
This next patch release will have binaries build with `CGO_ENABLED=0`. Please test those out to confirm the fix worked for you.
