### ISSUE TITLE
AIP-191 File names must not contain version numbers

### ISSUE THREAD

**Issue by parthea** [googleapis/api-linter#1326]
AIP-191 states `The version must not be used as a filename, because this creates bizarre imports in client libraries. Filenames such as v3.proto or v1beta1.proto are prohibited.` but the linter does not enforce this requirement.

https://google.aip.dev/191#file-names

**Comment by noahdietz** [comment]
This is already linted for https://linter.aip.dev/191/filenames

It's enforcement internally is another problem however...
