### ISSUE TITLE
AIP-123: google.api.resource plural field shouldn't be necessary for Singleton resources

### ISSUE THREAD

**Issue by noahdietz** [googleapis/api-linter#1333]
If we can detect that a resource definition represents a Singleton, the `plural` annotation shouldn't be necessary.

Unless we know there are use cases for it, or if we want to enforce its presence regardless of Singleton status, it should be excused.

**Comment by BrandonY** [comment]
GCS also ran into this one. We've got a singleton resource, and the linter wants us to give it a `plural` annotation that won't be used.

**Comment by noahdietz** [comment]
@BrandonY you know I was just thinking about this the other day, because there was a [YAQS](http://yaqs/5609854559959646208) regarding Singleton resources & pseudo-collection methods. There is technically a provision in AIP-156 that allows services to implement a Standard List + Reading across collections to list all Singleton resources for a parent collection: https://google.aip.dev/156#support-for-standard-list. I think we might want to still have it "just in case". I think it might seem silly at first but will be positive for future proofing. Going to bring it up in the next API design meeting

**Comment by noahdietz** [comment]
Ok we are going to require that Singletons also have the `plural` annotation for future proofing reasons, especially b.c there are viable uses for a plural singleton word (see above examples). Will need to update the AIP as well.

**Comment by BrandonY** [comment]
SGTM, thanks!
