### ISSUE TITLE
How do I use common imports?

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/api-linter#135]
@robcapo I tried to do this in a test...no dice...
<img width="843" alt="Screen Shot 2019-08-06 at 12 01 34 PM" src="https://user-images.githubusercontent.com/4346/62568558-5a121e80-b842-11e9-8aee-e681583d70f8.png">

**Comment by robcapo** [comment]
Hi Luke, try using AdditionalProtoPaths on the testutil function. Here's an example: https://github.com/googleapis/api-linter/blob/master/rules/rules_test.go#L23-L44

**Comment by lukesneeringer** [comment]
This worked.
