### ISSUE TITLE
Can someone help me read annotations?

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/api-linter#138]
Mostly hoping @noahdietz can help when he is back on Thursday.

I can not for the life of me read the `google.api.http` annotation properly. This is not really the fault of the linter, it is the fault of the fact that there are 2 `protoreflect` packages (and we use the one that has no search ranking), at least 4 separate official `descriptor` packages, a `proto` and `protobuf` package, and none of these actually work together in anything remotely approaching a sane way.

I committed the `aip-131-annotations` branch, which is in a non-working state. I spent all day trying to _just read one proto extention_ and I am asking for help, because between the utter lack of documentation and the fact that we overloaded every term six ways from Sunday, I really have no idea how to do it.

**Comment by mingzhi** [comment]
Hi Luke, I am copying an example from (Google internal) Code Search ([link](http://google3/ops/netops/faker/lib/googleapilite.go?l=887&rcl=251987419)):
```golang
opts := m.Options().(*dpb.MethodOptions)
v, err := proto.GetExtension(opts, apb.E_Http)
if err != nil {
  continue
}
r := proto.Clone(v.(proto.Message)).(*apb.HttpRule)
``` 
where `m` is a `MethodDescriptor` and `r` is a `HttpRule` message in the `http.proto`.

**Comment by lukesneeringer** [comment]
I found this internally, but I do not know what `dpb` is or how to import it. (I _think_ I figured out most of the others.)

**Comment by mingzhi** [comment]
Maybe this one (it is golang protobuf v2) for the 
descriptor proto :https://godoc.org/google.golang.org/protobuf/types/descriptorpb

**Comment by lukesneeringer** [comment]
That one _compiles_ at least, but populates `err` with:

    "proto: not an extendable proto.Message"

**Comment by lukesneeringer** [comment]
I am starting to suspect after reading things like [this issue](https://github.com/golang/protobuf/issues/794) that this may not be able to be done with Google's protoreflect right now.

I am taking an `Options()` message, unlike the OP on that bug, but it still clearly does not work, and it is telling when one of the authors suggests that there is not yet a (public) way to do this other than to use a third-party library.

**Comment by mingzhi** [comment]
Hi Luke, I figured out how to do that -- see [this example](https://github.com/mingzhi/extract-proto-annotation-example/blob/master/main.go). Note that we need to regenerate Go code for `annotations.proto` using `protoc-gen-go` [V2](https://godoc.org/google.golang.org/protobuf/cmd/protoc-gen-go) -- see [this script](https://github.com/mingzhi/extract-proto-annotation-example/blob/master/regen.sh). The [go-genproto](https://github.com/googleapis/go-genproto) currently is generated by the [V1](https://godoc.org/github.com/golang/protobuf/protoc-gen-go) plugin, which causes most of troubles when trying to integrate it to Golang protobuf V2.

Now in our linter, we have two options:
1. Send a PR to regenerate `go-genproto` using `protoc-gen-go` V2 (e.g., a new `v2` branch) or even create a go-genproto-v2 repo;
2. Generate those go codes in our repo, and migrate to `go-genproto` v2 later.

**Comment by noahdietz** [comment]
Just my two cents :)

> Generate those go codes in our repo, and migrate to go-genproto v2 later.

Yeah the relevant Go proto v2 bindings could be vendored in this repo, that would keep import paths the same and make removing it later easier. Also makes `go.mod` still relevant. We did this in the gapic-generator-go while our extension definitions were on a branch waiting to be merged. And considering these extension definitions don't change, maintenance would be low.

> Send a PR to regenerate go-genproto using protoc-gen-go V2

Talk to deklerk@, he maintains that repo and would know best how to proceed with a migration. Might take some time, thus I think 2 is the best stop gap while 1 is worked on.

> or even create a go-genproto-v2 repo

I don't think we want more Go protobuf repos. Again, talk to deklerk@ about the strategy here, he owns these things.

**Comment by lukesneeringer** [comment]
@neild was able to get me going on [the other issue](https://github.com/golang/protobuf/issues/794). Thanks all.
