### ISSUE TITLE
AIP-235: Linter doesn't allow 'hoisted' allow_missing field

### ISSUE THREAD

**Issue by jdtyner** [googleapis/api-linter#1404]
AIP-235 says "Other fields besides name may be "hoisted" from the standard Delete request." We hoisted `allow_missing` from our standard request, but the linter [does not allow the field.](https://linter.aip.dev/235/request-unknown-fields)

I see the same issue seems to have been [fixed for BatchUpdate already](https://github.com/googleapis/api-linter/issues/851).

**Comment by noahdietz** [comment]
Thanks for the report! Sent a patch
