### ISSUE TITLE
AIP-140: Abbreviations are not mentioned in AIP

### ISSUE THREAD

**Issue by SanjayVas** [googleapis/api-linter#1453]
`core::0140::abbreviations` checks for abbreviations, but this is not mentioned in the text of AIP-140. For example, the linter checks that "statistics" is always abbreviated as "stats", but that's not mentioned in the AIP.

**Comment by noahdietz** [comment]
Thanks for filing this. Seems like the abbreviations recommendation actually comes from the older naming convention guidance: https://cloud.google.com/apis/design/naming_convention#name_abbreviation

This wasn't ported to the AIP. This should be a fix in the AIP itself. I'll close this in favor of https://github.com/aip-dev/google.aip.dev/issues/1464
