### ISSUE TITLE
Shorten command-line arguments

### ISSUE THREAD

**Issue by mingzhi** [googleapis/api-linter#165]
@jgeewax and @lukesneeringer, I propose to shorten the command line to `api-lint [command options] files...` instead of `api-linter checkproto [command options] files...`, i.e., I will remove sub-commands (`checkproto`). There will be some amount of code changes, so I would like to have a nod from both of you first. Thanks!

**Comment by robcapo** [comment]
Are we still considering having a subcommand like `api-lint rules` to list out all the possible rules a user can configure?

**Comment by mingzhi** [comment]
I think we can use a `-list_rules` flag.

**Comment by lukesneeringer** [comment]
1. Fine with `api-lint` as the binary's name.
2. Fine with making `checkproto` implied.
3. Fine with something like `--list-rules`, but please use all `kebab-case` (no underscores) as is generally common in the external world.

**Comment by mingzhi** [comment]
Done.
