### ISSUE TITLE
Enable rule developers to easily return problems on package / syntax.

### ISSUE THREAD

**Issue by robcapo** [googleapis/api-linter#166]
Developers should have an easy way to return a problem with the location of the `package` and `syntax` directives.

**Comment by lukesneeringer** [comment]
The original code for this was [here][1] (I too aggressively culled it).

  [1]: https://github.com/googleapis/api-linter/blob/9c470de43f578f409f8427d906d279463376e55d/lint/source.go

**Comment by lukesneeringer** [comment]
Fixed in #195.
