### ISSUE TITLE
AIP-124: Message names / naming format

### ISSUE THREAD

**Issue by robcapo** [googleapis/api-linter#176]
**Note:** this AIP is not yet written.

Old linter rule: https://g3doc.corp.google.com/google/api/tools/linter/g3doc/rules/naming-format.md?cl=head

**Comment by lukesneeringer** [comment]
Please do not do this one until I get the AIP written.

**Comment by lukesneeringer** [comment]
I am not sure what this was actually about, and the link is gone. Whups. It clearly was not critical.
