### ISSUE TITLE
Internal Google Linting

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/api-linter#187]
Hey, #186 got merged before I saw it, and I have concerns.

If GitHub is our source of truth, we can not expect (potentially external) rule authors to conform to arbitrary lint rules that are not enforced here. This is going to be a consistent problem.

I would argue that:

1. We should probably enforce linting here (as we already do).
2. We should probably disable any linting in google3. It should accept whatever code is accepted here, with only the modifications required to get it running in google3.

**Comment by robcapo** [comment]
I think it's a valid point. In general most of the justification for lint rules in google3 are to make it easier for the tools to do stuff for us automatically. All other things being equal, I think is worth following just to make sync tasks easier. [Here's](http://go/gocomments#imports) the section on imports. There's not a great explanation of what exactly we get for pb aside from `goimports` understands it, but the cost of following the convention is pretty small out here.

**Comment by robcapo** [comment]
I do agree though, if there's some way we can get the lint rules to execute on GitHub, it would be much better for us.

**Comment by mingzhi** [comment]
I am confused: why cannot we, as code owners and maintainers, clean up codes for better quality and readability?

I agree that finding a way to enforce internal styles here is better. But the bottom line is:

If some Google styles are too far-reached, we can always ignore those errors in the critique and (force) submit the syncing CL (and it is a common practice during importing third-party repos in Google).

**Comment by mingzhi** [comment]
I want to underscore that we don't force external contributors to stick with our internal-only styles, but we have the choice to maintain our code base being consistent with our internal requirements -- the burden is always on us.

**Comment by lukesneeringer** [comment]
> I think it's a valid point. In general most of the justification for lint rules in google3 are to make it easier for the tools to do stuff for us automatically. All other things being equal, I think is worth following just to make sync tasks easier. Here's the section on imports. There's not a great explanation of what exactly we get for pb aside from goimports understands it, but the cost of following the convention is pretty small out here.

Sure, I do not mind following the conventions. My issue is that I want tooling to enforce it, and ideally I also want to be able to lint for it when I am writing code. One of the pleasant things about Go is that I hit Ctrl+S and VS Code just magically reformats erverything to make the linter happy. We lose that if we have hidden linting rules.

> I am confused: why cannot we, as code owners and maintainers, clean up codes for better quality and readability?

Because effectively we will be constantly doing it. I am fine with enforcing rules, but I want them to be enforced in code in CI on GitHub.

**Comment by mingzhi** [comment]
Totally agree with CI and tooling in Github. I think we can ask around (we have many other Google owned Go repo syncing between Github and Google). Thanks!

**Comment by lukesneeringer** [comment]
@jgeewax, @robcapo, @mingzhi and I discussed this in person last week.

We agreed:

1. We should try to see if we can do any currently-internal checks here.
2. Regardless of the answer to (1), internal linting should always be disabled in third_party in google3.
