### ISSUE TITLE
Change --proto-descriptor-set to StringArrayVar

### ISSUE THREAD

**Issue by bufdev** [googleapis/api-linter#317]
Just a suggestion from perusing the code:

What do you think of changing `--proto-descriptor-set` to a `StringArrayVar` and not relying on `:` for splitting? Relying on `:` may cause issues with Windows down the road, or if you wanted to be able to do i.e. `--proto-descriptor-set https://gcs.yourcompany.com/path/to/bucket/fd.pb`. There's other `StringArrayVar` declarations so it might make sense.

Also not that I'm always in favor of copying `protoc`, but perhaps name it `--descriptor-set-in`?

**Comment by lukesneeringer** [comment]
I am +1 for this suggestion.

**Comment by mingzhi** [comment]
I am Okay with this suggestion. Actually I was self-debating about the naming, being consistent to `--proto-path` or `protoc`. In the end, I just threw a coin and made the call :)

**Comment by mingzhi** [comment]
Done.
