### ISSUE TITLE
request-unknown-fields documentation neglects "etag" field

### ISSUE THREAD

**Issue by BrandonY** [googleapis/api-linter#409]
https://aip.dev/134 specifies that update methods should use a field named "etag" in some circumstnaces, but https://linter.aip.dev/134/request-unknown-fields specifies only resource, update_mask, and request_id as valid field names.

**Comment by lukesneeringer** [comment]
The etag should be in the resource itself in that case, should it not?

**Comment by BrandonY** [comment]
Ah, yes, I misread that.
