### ISSUE TITLE
API Lint rule 126, Should not check for alias enum type

### ISSUE THREAD

**Issue by greynutw** [googleapis/api-linter#466]
if the first enum type is also an alias, then an API lint error will occur. Say enum Type { option allow_alias = true; TYPE_UNSPECIFIED = 0; DEFAULT_TYPE = 0; TYPE_ONE = 1; } This type enum alias, in my understanding should be allowed.

**Comment by lukesneeringer** [comment]
Good catch. I will fix this. :-)
