### ISSUE TITLE
Parent is required even for top-level resources

### ISSUE THREAD

**Issue by jiangk** [googleapis/api-linter#483]
The following linters:

- https://linter.aip.dev/133/method-signature
- https://linter.aip.dev/133/http-uri-parent

expect Create methods to always have a `parent`.

Should the linters not warn on missing `parent` when the resource is a top level resource/collection item?

> A parent field must be included **unless the resource being listed is a top-level resource**. 
(https://aip.dev/133)

**Comment by lukesneeringer** [comment]
This is a good question and I am not sure what the best answer is here. The old linter also complained about this, but it was a Cloud-specific rule (any parent other than `project` got a complaint).

I _think_ the right answer here might be to make the rules here more lenient but add a Cloud-specific rule around projects and locations. Thoughts?

**Comment by alexcepoi** [comment]
+1

**Comment by SandroGolis** [comment]
+1
