### ISSUE TITLE
Batch methods showing errors in URL pattern

### ISSUE THREAD

**Issue by jgeewax** [googleapis/api-linter#485]
Apparently RPCs (like `rpc BatchVerb`) show errors saying that the custom method should be `:batch` (and not `:batchVerb`).

I haven't verified this, it came from an internal Google source (b/147516738 for those with access)

Assigning to Luke to verify.

**Comment by lukesneeringer** [comment]
I fixed this recently in #477 but forgot to update the internal bug. Doing that now.
