### ISSUE TITLE
File-layout docs incorrect for enums

### ISSUE THREAD

**Issue by davis-haba** [googleapis/api-linter#486]
The [docs for file layout](https://linter.aip.dev/191/file-layout) states:

> Messages appear below top-level enums.

However, [the implementation](https://github.com/googleapis/api-linter/blob/master/rules/aip0191/file_layout.go#L38) (and error message) states the opposite --that  enums should be below messages. 

I believe the docs should say: "Messages appear **above** top-level enums".

**Comment by lukesneeringer** [comment]
Yep, the docs are wrong and the implementation is correct.
