### ISSUE TITLE
[AIP-158] Be stricter about pagination.

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/api-linter#490]
We need a lint rule (and amendment to AIP-158 itself) that will enforce the following:

For all messages that:
* end in `Response`
* Contain a `next_page_token` field.

Throw a linter warning if:

* The _first_ field in the message (by both position and field number) is not repeated
* The _first_ field in the message is a primitive
* The _first_ field in the message is not named according to `plural(message_name.to_snake().split('_')[1:-1])`

These should probably all be separate rules.

**Comment by Dos-Ph** [comment]
I will send PR for this.

**Comment by lukesneeringer** [comment]
This is done now.
