### ISSUE TITLE
Missing domain name guidance for documentation link html

### ISSUE THREAD

**Issue by summer-ji-eng** [googleapis/api-linter#505]
Th [linkinator](https://www.npmjs.com/package/linkinator) detects broken links in nodejs client library ([detail](https://docs.google.com/document/d/1IW6sNboGZrdwo6YNyM8r5XNikYdI2UPeUF4CrHe8rYU/edit#bookmark=id.snbahxiz111f)).  Fixed the broken links by adding prefix "https://cloud.google.com"(absolute links) for each links in upstream protos [example](https://critique-ng.corp.google.com/cl/296325352/depot/google3/google/cloud/dataproc/v1/clusters.proto).

AIP 192 guide the documentation link, it seems to missing guidance to use fully qualified domain name. In the above example, use relative link in a proto that assumes `cloud.google.com` cause the problem.

If we have linter earlier in the pipeline to catch these kinds of problems, will be fantastic.

**Comment by lukesneeringer** [comment]
We have this in [AIP-192](https://google.aip.dev/192) now. It might be hard to lint for though. :-/

**Comment by apasel422** [comment]
Wasn't this fixed by #530?

**Comment by lukesneeringer** [comment]
Only partially. It will catch a Markdown link, but not someone writing `/apis/foo.html` in plain text.
That said, I think linting for that is infeasible, so I am going to close this.
