### ISSUE TITLE
Custom Methods starting with standard verb

### ISSUE THREAD

**Issue by ialcor** [googleapis/api-linter#517]
Right now, the logic for stating whether a method is a `custom method `is based on the suffix on its HTTP URI. If it has a URI suffix it's considered custom. If it does not have a URI suffix then the verb is checked and if it's not a standard verb it's considered custom. 

On the other hand, the logic to decide if a method is a `standard method` is based on the verb in the method name only. If it's a standard verb it's considered standard.  

Thus, cases like:
```
rpc UpdateAccessPointFirmware(inputRequest) returns  (outputResponse) {
        option (google.api.http) = {
            post: "/v1/{name=installations/*/access-points/*}:update-firmware"
            body: "*"
        };
}
```
are evaluated as both, `Updated standard method `and `custom method`. Linting rules for both AIP134 and AIP136 are applied.  (`:update_firmware` is found so it's taken as custom, at the same method name starts with `update` so it's taken as standard update method)

I think this is not the right behavior.  A solution would be to implement one extra check inside every AIP related to standard methods `(131-135),` so that as well as checking the verb in the name (`update` in this case), it also checks that the method is not custom before tagging the method as a  standard method.

**Comment by lukesneeringer** [comment]
I think the thing we really need here is rule inter-dependency -- certain rules should fire only if others fire, pass, or fail. This is a reasonably complex addition, though. As a stop-gap, we can probably add prefix checks on the custom method checks.

That said, to some extent this is the linter doing its job -- this is something you should not be doing. The example that you give looks more like a [singleton](https://aip.dev/156).

**Comment by lukesneeringer** [comment]
I think we have since fixed this issue.
