### ISSUE TITLE
Figure out whether column indices should be 1 or 0 based

### ISSUE THREAD

**Issue by jgeewax** [googleapis/api-linter#52]

**Comment by lukesneeringer** [comment]
For what it is worth, VS Code uses 1-indexing.

**Comment by mingzhi** [comment]
Both line and column are 1-indexing.

**Comment by lukesneeringer** [comment]
I did a quick survey and it looks like every editor I can find uses 1-indexing. Ergo, I assert we should too.

**Comment by mingzhi** [comment]
Okay, I closed it as we are already using 1-indexing. Thank you Luke!
