### ISSUE TITLE
Exit Status Code = 0 when linting problems are found

### ISSUE THREAD

**Issue by ialcor** [googleapis/api-linter#522]
Right now, wether problems are found during linting process or are not, the program finishes with status code 0. This could be understood as the right behavior. 

However,  making the api-linter fail when problems are found could be helpful, it could help integrating api-linter into CI stages for example.  What do you think?

This capability to fail after problems are found could be activated conditionally, via input parameters to the linter.  This is a standard practice for some linter. 

example: 

>  api-linter someproto.proto -I some path --set_exit_status (print problems and then exit with code 1)
>  api-linter someproto.proto -I some path (print problems and exit correctly)

What do you think? I have some implementation and I could open a PR if you agree.

**Comment by mingzhi** [comment]
+1. Can you open a PR? Thanks!

**Comment by lukesneeringer** [comment]
My vote is for an exit status of 1 if there are problems; I agree with a switch to make it 0 if needed.

**Comment by lukesneeringer** [comment]
Fixed in #534.
