### ISSUE TITLE
For resource which does not have plural, should method be plural?

### ISSUE THREAD

**Issue by hycui090** [googleapis/api-linter#527]
According to the the collection-identifier guide, for word without plural style, should be kept as non-plural, like info. https://aip.dev/122#collection-identifiers
But the api-linter will fail the method name ListStitchInfo and its response type ListStitchInfosResponse. What is the correct naming for such case.

**Comment by lukesneeringer** [comment]
`ListStitchInfoResponse` is correct (although I would argue that resources ending in -Info are probably an anti-pattern). I will check on the rule implementation.

**Comment by lukesneeringer** [comment]
I checked and the rule implementation matches what I said it did.
