### ISSUE TITLE
How do we deal with versioning of the linter binary?

### ISSUE THREAD

**Issue by jgeewax** [googleapis/api-linter#53]

**Comment by lukesneeringer** [comment]
Here is what we do for our Go-based testing tool: https://github.com/googleapis/gapic-showcase/blob/master/.circleci/config.yml

I recommend that. :)

**Comment by mingzhi** [comment]
> Here is what we do for our Go-based testing tool: https://github.com/googleapis/gapic-showcase/blob/master/.circleci/config.yml
> 
> I recommend that. :)

Yup, I borrowed a tiny part from it -- definitely need to bring more.

**Comment by QuantumNovice** [comment]
What about SVN?
https://help.github.com/en/articles/support-for-subversion-clients
