### ISSUE TITLE
Custom methods URI suffix for top-level collections

### ISSUE THREAD

**Issue by orkun1675** [googleapis/api-linter#532]
Hello,

We have a custom method acting on a top-level collection, we have the URL path set like so:

`post: "/v1alpha1/books:search"`

However, this format is not accepted by https://linter.aip.dev/136/http-uri-suffix. The alternative looks ugly and hard to read since it doesn't live under the collection:

`post: "/v1alpha1:searchBooks"`

The AIP page, https://aip.dev/136, that resulted in this rule is also not very clear on how to name URI suffixes that act on top-level collections.

**Comment by lukesneeringer** [comment]
Oh, right -- it wants a "parent" variable to accept this. It should also accept no variable.
