### ISSUE TITLE
check if java_outer_classname is set to proto filename

### ISSUE THREAD

**Issue by ialcor** [googleapis/api-linter#535]
According to [AIP191](https://aip.dev/191):

> The java_outer_classname annotation must be set, and should be set to the name of the proto filename, in PascalCase, with Proto appended. Example: LibraryProto.

Right now, the implemented rule only checks if java_outer_classname is set. In case it is, it does not check if it set to the filename as is recommended by the AIP191.

I think we could include this checking.

**Comment by lukesneeringer** [comment]
Concur, this seems reasonable to do.

**Comment by ialcor** [comment]
I have been trying some easy solution around this and arrive to a tricky point. 

We have some protofile names formed by compound names. For example :`mobile + key` or  `access+key`. If I am not wrong, naming convention suggest that this protofiles should be named `mobilekey.proto` and `accesskey.proto`.

According to what i think are the naming conventions again ( I may be wrong), `java_outer_class` option on this two files should be:  `MobileKeyProto` and `AccessKeyProto`. 

Being able to detect the right naming gets tricky because of the casing.

Solutions to this could came by:

* 1- making the linting rule not case sensitive
* 2- changing protofile names to something `mobile_key.proto` and `accees_key.proto`. (Changing our protofile names because of a linting rule does not seems reasonable.)

Any suggestions?

**Comment by lukesneeringer** [comment]
The right answer here is (2): for the proto files to be `mobile_key.proto` and `access_key.proto`, but obviously if you have already published them, that ship has sailed.

It might be wise to make the lint rule case insensitive anyway.
