### ISSUE TITLE
Extraneous line in documentation code example

### ISSUE THREAD

**Issue by gsmith98** [googleapis/api-linter#547]
https://github.com/googleapis/api-linter/blob/master/docs/rules/0203/output-only.md

The code snippet in the "Disabling" category has the comment line "// Immutable. The title of the book." which does not apply to that example. My guess is that this code example was originally copied from 203/immutable and this line was missed. 

This is also the only disabling example in 203 where there is a comment between the not-precedent comment and the field in question.

**Comment by lukesneeringer** [comment]
That is exactly what happened. Thanks.
