### ISSUE TITLE
Linter complains about a 'time_zone' field of type google.type.TimeZone

### ISSUE THREAD

**Issue by ebf42** [googleapis/api-linter#590]
Given a field named "time_zone" of type [google.type.TimeZone](https://github.com/googleapis/googleapis/blob/5dedfae4a499e90f6da806eb3536811e7c319a41/google/type/datetime.proto#L91), stating it should have type string instead. This seems like a bug; if anything, it seems like google.type.TimeZone would be preferable since it's more self-describing.

**Comment by wj-chen** [comment]
+1
