### ISSUE TITLE
Update lints for parent-less batch methods

### ISSUE THREAD

**Issue by apasel422** [googleapis/api-linter#615]
Now that https://github.com/aip-dev/google.aip.dev/issues/599 is fixed, we should update the following lints to account for the optional `parent` field:
- https://linter.aip.dev/136/http-uri-suffix
- https://linter.aip.dev/231/http-uri-suffix
- https://linter.aip.dev/231/request-parent-field
- https://linter.aip.dev/233/http-uri-suffix
- https://linter.aip.dev/233/request-parent-field
- https://linter.aip.dev/234/http-uri-suffix
- https://linter.aip.dev/234/request-parent-field

**Comment by lukesneeringer** [comment]
Starting to work on this, but why is the AIP-136 rule affected? (I can not see any obvious change to make.)

**Comment by apasel422** [comment]
https://github.com/googleapis/api-linter/blob/9a793b531cffe0a982c9db350b68f59beedb8d2b/rules/aip0136/http_uri_suffix.go#L54-L61 doesn't work right if the batch method doesn't have the `parent` field in the URI.

**Comment by lukesneeringer** [comment]
Got it, thanks. Added to #619.

**Comment by apasel422** [comment]
This issue should be reopened, as the `http-uri-suffix` rules for AIPs 231, 233, and 234 weren't updated to account for `parent`-less paths. For example, the following still triggers a lint error:

```proto
service Library {
  rpc BatchGetBooks(BatchGetBooksRequest) returns (BatchGetBooksResponse) {
    option (google.api.http) = {
      get: "/v1/books:batchGet"
    }
  }
}
```
