### ISSUE TITLE
Getting "Timestamp field names" error for non Timestamp field

### ISSUE THREAD

**Issue by ryoullar** [googleapis/api-linter#616]
Receiving the following error
https://linter.aip.dev/142/time-field-names

But the field in question is a custom proto message, not a Timestamp. The message in question does not include a Timestamp either.
It is something along the lines of:
User updated_user = 1;

**Comment by lukesneeringer** [comment]
Are you sure you are on a current version? It looks like we only run this rule on specific types (Timestamp, string, int32, int64). The applicable code is [here](https://github.com/googleapis/api-linter/blob/master/rules/aip0142/time_field_names.go#L29-L31), and test [here](https://github.com/googleapis/api-linter/blob/master/rules/aip0142/time_field_names_test.go#L38).

Closing for now -- reopen if you have more information.

**Comment by ryoullar** [comment]
I'm not sure which version we're on, but it looks like it might be 1.20.

The message type is "UserAccess", it is certainly not any of those listed in the code you cited.
