### ISSUE TITLE
AIP-203. False detection [2]

### ISSUE THREAD

**Issue by valery-barysok** [googleapis/api-linter#634]
It creates a lot of noise messages and it leads to usability issue. Can you provide examples when you really need to complain for OutputOnly field behavior in the same time if it is already matched for Required field behavior?

I believe it should be more intelligent.

Based on https://github.com/googleapis/api-linter/issues/621

**Comment by lukesneeringer** [comment]
Closing in favor of #621 (sorry, I did not know you could not reopen things).
