### ISSUE TITLE
Linter rule about Base64 fields doesn't actually appear in AIP-140

### ISSUE THREAD

**Issue by ebf42** [googleapis/api-linter#639]
https://linter.aip.dev/140/base64 says the rule, "tries to enforce that base64 fields use the bytes type, as mandated by AIP-140."

But looking at https://google.aip.dev/140, there is no mention of base64 nor anything about the use of string vs bytes data type.

Is this captured in a different AIP? Or is this an old rule that went away? Or a rule that was drafted but never finalized? (Or am I just missing something?)

**Comment by apasel422** [comment]
Indeed, the only mention of base64 at all in any AIP is https://google.aip.dev/158#opacity.

**Comment by apasel422** [comment]
Fixed in https://github.com/aip-dev/google.aip.dev/pull/735.
