### ISSUE TITLE
AIP-144: Declarative-friendly resources should not have Add/Remove methods for repeated fields.

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/api-linter#669]

**Comment by apasel422** [comment]
Where is this guidance documented? I don't see any mention of it in AIP-144.

**Comment by lukesneeringer** [comment]
Good catch, will need to add it there. I must have missed it when making the AIP changes from the internal Google Doc.

**Comment by lukesneeringer** [comment]
aip-dev/google.aip.dev#647

**Comment by lukesneeringer** [comment]
That said, I am going to punt on this one. Too hard to map `AddFoo` to the `Bar` resource. I may revisit it later.
