### ISSUE TITLE
GitHub action for api-linter

### ISSUE THREAD

**Issue by ewhauser** [googleapis/api-linter#709]
I've developed a GitHub action for api-linter that I'd be happy to open source. However, because of the way GitHub actions are structured (you need to check in your nodejs `dist` directory directly into the source tree), I'm not sure if would make sense to host it as a part of this repo. Most likely, it would make more sense for it to be hosted under `googleapis/api-linter-action`.

Let me know if there is interest. Thanks.

**Comment by lukesneeringer** [comment]
Hi @ewhauser, sorry for not getting back to you sooner. (I have been in the process of a move and generally not been responsive.)

Thanks for doing this, and I love the idea. I do not know very much about _writing_ GitHub actions, although I have configured and used them. I would be happy to host it in this repo and also happy to create a repo to host it. Perhaps send a PR to this repo and, provided it does not interfere with the core linter, I see no reason not to accept it.

One legal thing: Anything that goes into _any_ repo under googleapis has to have a signed CLA and have a Google copyright and Apache license. I personally have no say or control over that. But, if you are okay with that, I would love to accept it.

**Comment by ewhauser** [comment]
@lukesneeringer - Since writing this and spending some more time with GitHub Actions, I think the best approach would be to do what [golangci-lint](https://github.com/golangci/golangci-lint) does and have an output format that uses the GitHub Actions format and then have an action that is a simple wrapper around the CLI tool (a la https://github.com/golangci/golangci-lint-action).

I believe the best approach to create the action itself would be to create a new repository called `api-linter-action`. I haven't seen any other examples were actions were not in their own repo.

Happy with whatever licensing / CLA needs to be signed.

**Comment by lukesneeringer** [comment]
Okay, I will see about getting that set up.

**Comment by lukesneeringer** [comment]
As a sanity check, would it be better for you to just host the action yourself, and we just add documentation in the linter to advertise it?

I am still happy to make a repo, but it seems like if you wrote it, it should stay "yours".

**Comment by ewhauser** [comment]
I think that's reasonable. Will submit a PR for the output formatting. Thanks!

**Comment by lukesneeringer** [comment]
Sounds good!

**Comment by lukesneeringer** [comment]
Hey @ewhauser, I am going to close this since it has been sitting around for a bit. Still feel free to submit a PR to point to your GitHub Action once you are ready!

**Comment by juchaosong** [comment]
I've pushed [api-linter](https://github.com/marketplace/actions/api-linter-setup) to marketplace.
