### ISSUE TITLE
Integrations with IDEs?

### ISSUE THREAD

**Issue by jankrynauw** [googleapis/api-linter#764]
Hi

Are there any integrations with IDEs?  In particular any of the Jetbrain IDEs' (Goland, etc.)

**Comment by tam7t** [comment]
This is my vscode [task](https://code.visualstudio.com/docs/editor/tasks): https://gist.github.com/tam7t/fe109fe8f6916e24a971f6017e7119ef

I used `jq` to rework the output to make it easier to parse with vscode's problemMatcher.

**Comment by lukesneeringer** [comment]
This is the type of thing I would be happy to publish, but lack time to write.

**Comment by jankrynauw** [comment]
We just created our own plugin for this: https://plugins.jetbrains.com/plugin/16164-aip-linter

**Comment by lukesneeringer** [comment]
Hey, awesome. Is it okay if we add this to the documentation somewhere?

**Comment by jankrynauw** [comment]
No problem👍🏻

**Comment by fredrikaverpil** [comment]
In case anyone of you are on Neovim, you can lint your protos using nvim-lint soon 😄
https://github.com/mfussenegger/nvim-lint/pull/665
