### ISSUE TITLE
AIP-128, AIP-156, AIP-164, AIP 148: Singleton resources in Declarative Friendly APIs have unexpected warnings

### ISSUE THREAD

**Issue by tylerg-dev** [googleapis/api-linter#791]
When using Declarative Friendly API [AIP-128](https://google.aip.dev/128) and Singleton Resources [AIP-156](https://google.aip.dev/156) at the same time the linter raises warnings that likely it shouldn't.

1) [AIP 164](https://google.aip.dev/164) Declarative Friendly entities typically require soft-delete and undelete, but this will often not make sense for Singleton resources.  In particular [AIP-156](https://google.aip.dev/156) requires that Singletons not define a Delete verb:
> Singleton resources must not define the Create, List, or Delete standard methods. The singleton is implicitly created or deleted when its parent is created or deleted.

2) [AIP 148](https://google.aip.dev/148) Declarative Friendly entities require delete_time (since resource with soft-delete and undelete defined are expected to have it), but Singleton are expected to not have delete verbs as above.

**Comment by lukesneeringer** [comment]
Ohoho, thanks for this report! We have written a lot of these rules but they have not seen very much real world use. Will get these addressed ASAP.

**Comment by apasel422** [comment]
`core::aip0164::declarative-friendly-required` only reports a problem if a declarative-friendly resource has a `Delete` method but no `Undelete` method, so I don't think it needs to be changed:

https://github.com/googleapis/api-linter/blob/c18f3154970793d9b984a376344d44e73ee4eb39/rules/aip0164/declarative_friendly_required.go#L24

But I'm working on a fix for to prevent `core::aip0148::declarative-friendly-fields` from requiring a `delete_time` field for singleton resources.
