### ISSUE TITLE
Should aip0151::lro-response-reachable inspect transitive dependencies?

### ISSUE THREAD

**Issue by apasel422** [googleapis/api-linter#793]
Right now, it only examines top-level ones:

https://github.com/googleapis/api-linter/blob/e14522eeadf175952b406c441f9f2c6978e68af1/rules/aip0151/lro_response_reachable.go#L47-L54

**Comment by lukesneeringer** [comment]
Yes, and the AIP-123 check for resource references should too, if it does not already.

**Comment by lukesneeringer** [comment]
Sorry, AIP-124. Actually, that one already does check transitive dependencies. So [this code](https://github.com/googleapis/api-linter/blob/main/rules/aip0124/valid_reference.go#L67) should move into utils so it can be used in AIP-151.
