### ISSUE TITLE
Error levels

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/api-linter#82]
As best as I can tell, `lint.Problem` lacks any concept of an error level.
Most linters support both warnings and errors, and we presumably should also (e.g. warn for "shoulds", error for "musts").

Most linters also have an "error on warnings" setting.

**Comment by mingzhi** [comment]
We are using `Category` in `Problem` as a proxy for error levels, e.g., a category can be `error`, `warning`, or `commit_blocking`. We let users to define the category for each rule in their rule configuration. But we can provide a default for each rule.

**Comment by lukesneeringer** [comment]
Got it, that makes sense. I just did not realize what `Category` meant.
Are the values strings?

**Comment by mingzhi** [comment]
Yes, they are strings -- we don't want to pre-define categories -- it is up to users to define them in their configuration, so they can develop/use downstream tools to target their categories. For example, some teams may want to use presubmit check to target the violation of some rules of their defined category (e.g., category: "my-team-want-to-enforce-these-rules").

**Comment by lukesneeringer** [comment]
Okay, I am happy with that.
