### ISSUE TITLE
Test for every rule having a test case

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/api-linter#83]
I am struggling to understand `TestEveryRuleHasATestCase`.

I added three rules, and a test case for each (in #80).
CI still fails saying that not every rule has a test case, which appears to point to [this code](https://github.com/googleapis/api-linter/blob/master/cmd/api-linter/integration_test.go#L35), which requires a yet-different test case for each rule?

General comment: We should expect O(10000) rules. I agree that they should all have test cases, but this piece here seems to expect something different, and alarmingly it wants it in a single file. That will not scale.

**Comment by mingzhi** [comment]
It is meant for integration test -- we don't need to test the detailed logic there, but to test if it can be integrated into the linter, especially to check if an added rule can be enabled/disabled in the user configuration and in-file comments.

**Comment by lukesneeringer** [comment]
Why does that need to be done for literally every rule? The logic is master logic that is all in one place, is it not?

**Comment by mingzhi** [comment]
I can see the annoying part -- it needs adding a (somehow redundant) test case when creating a rule, also needs removing the test case when the rule is removed or disabled. We should have a better way for integration test.

**Comment by lukesneeringer** [comment]
It is that, and also the number of rules will be _large_.
I just counted on [AIP-131](https://aip.dev/131), and that AIP alone is going to have 8 rules. Assume a general 1:10 ratio of AIPs to rules for many others (although some AIPs may have no rules, e.g. [AIP-121](https://aip.dev/121)).

I fully expect 1,000 or more rules by the end of 2020, so anything we do needs to scale well to that.

**Comment by lukesneeringer** [comment]
@mingzhi @robcapo Okay, now having written 8 rules, I want to officially request to kill this test, unless it is needed. I totally get that the integration tests have value, but _this specific rule_ seems overwrought.
