### ISSUE TITLE
Linter crashes when ListResponse is repeated string

### ISSUE THREAD

**Issue by tamayika** [googleapis/api-linter#854]
Confirmed on 1.25.0.  error is `runtime error: invalid memory address or nil pointer dereference`.

```proto
syntax = "proto3";

message ListBooksRequest{}
message ListBooksResponse{
  repeated string books = 1;
}
```

* If I delete ListBooksRequest, linter does not crash.

**Comment by apasel422** [comment]
Do you have access to a stack trace for this crash?

**Comment by tamayika** [comment]
No stacktrace generated, only error message is shown.
Is there any option to show stacktrace or verbose option?

**Comment by apasel422** [comment]
The error is in `rules/aip0132/request_show_deleted_required.go`. Specifically, we are assuming that the field is a message type, when in this case it is a `string`. Working on a fix now.
