### ISSUE TITLE
AIP-123 seems to make too many structures invalid

### ISSUE THREAD

**Issue by Ark-kun** [googleapis/api-linter#863]
This rule essentially disallows using field "name" in any proto message.
Name is a general word which is used in many structures unrelated to Google Cloud resources and their IDs.
The Google Cloud Vertex Pipelines API is now considered invalid by the linter.

P.S. I'm not sure that the "name" is the best term for a full resource ID. It might be confusing for some of the people. Perhaps we could have used a different naming for the fully-qualified resource IDs.

**Comment by lukesneeringer** [comment]
Yep, true facts. I wish we had not made this decision years ago, but we did and therefore we are stuck with it. :-(
