### ISSUE TITLE
AIP-126: Linter complains about having UNKNOWN as the first value

### ISSUE THREAD

**Issue by manjunathganga** [googleapis/api-linter#871]
Linter complains about not having [UNSPECIFIED](https://linter.aip.dev/126/unspecified) as the zero value even if `UNKNOWN` is specified as the first enum value. 
[AIP-126](https://google.aip.dev/126#guidance) allows having `UNKNOWN` as the zero value and it is a meaningful default for our use case. Can the linter be updated to allow this value?

Thanks.

**Comment by apasel422** [comment]
Related to my question at https://github.com/aip-dev/google.aip.dev/issues/729.

**Comment by noahdietz** [comment]
We confirmed that this is an exception to the AIP, so we need to add it in as an exception to the existing rule.
