### ISSUE TITLE
Description of API linter for AIP 191 is incorrect

### ISSUE THREAD

**Issue by slaweg** [googleapis/api-linter#916]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Is this a client library issue or a product issue? We will only be able to assist with issues that pertain to the behaviors of this library. If the issue you're experiencing is due to the behavior of the product itself, please visit the [Support page](https://cloud.google.com/support) to reach the most relevant engineers.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - Programming language: any
  - OS: any
  - Language runtime version: any
  - Package version: any

#### Steps to reproduce

  1. Visit https://linter.aip.dev/191/file-layout
  2. Check that the AIP 191 description of the linter finding says `Top-level enums appear above messages.`
  3. Visit https://google.aip.dev/191#file-layout
  4. Check that AIP 191 places all top-level enums at the bottom of the file (below messages).
  5. Compare description in AIP linter 191 documentation page with AIP 191 documentation page.

Possible fixes:
- Rephrase documentation to  `Top-level enums appear below messages.`

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by shwoodard** [comment]
This bug is invalid. The documentation says, `this rule currently complains if:` before it says `Top-level enums appear above messages.`.  This means, the following: "this rules validates that top-level enums appear below messages".

This is also what the linter validates for **and** also matches [the aip](https://google.aip.dev/191#file-layout).
