### ISSUE TITLE
Example is missing the config file

### ISSUE THREAD

**Issue by pcj** [googleapis/api-linter#92]
Docoumentation refers the user to `example.sh`:

```
api-linter check --cfg ./example_config.json example_bad_naming.proto
```

However I could not find the `example_config.json` file.  Did I just completely miss it?  Maybe it was not checked in?

**Comment by mingzhi** [comment]
I think I deleted it accidentally -- I will add it back -- right now, you can remove the `--cfg` flag. Thanks!
